### ISSUE TITLE
ReferenceError: "AdsManagerApp" is not defined. (file Code.gs, line 136)

### ISSUE THREAD

**Issue by MichaelHelms8** [google/agency-ads-management-solutions#2]
New to GitHub so apologies if this is not the right way to use this.

I'm trying to run the ETA to RSA script, I've made it work on an account that sits within an MCC, however can't get it to work when the account is a stand alone with no MCC. I'm getting: ReferenceError: "AdsManagerApp" is not defined. (file Code.gs, line 136)

Is there anything I should change to make this work?

**Comment by kondie** [comment]
This code is intended to be installed in a Google Ads Manager Account(MCC).

For your case, you can modify the main function to remove all references to AdsManagerApp... e.g. remove lines 136 to 143 and replace it with directly invoking generateResponsiveSearchAdsForAccount function.
